/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AddFuelRouteImport } from './routes/add-fuel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogsIdRouteImport } from './routes/logs.$id'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AddFuelRoute = AddFuelRouteImport.update({
  id: '/add-fuel',
  path: '/add-fuel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIdRoute = LogsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-fuel': typeof AddFuelRoute
  '/analytics': typeof AnalyticsRoute
  '/expenses': typeof ExpensesRoute
  '/logs': typeof LogsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/trips': typeof TripsRoute
  '/vehicles': typeof VehiclesRoute
  '/logs/$id': typeof LogsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-fuel': typeof AddFuelRoute
  '/analytics': typeof AnalyticsRoute
  '/expenses': typeof ExpensesRoute
  '/logs': typeof LogsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/trips': typeof TripsRoute
  '/vehicles': typeof VehiclesRoute
  '/logs/$id': typeof LogsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-fuel': typeof AddFuelRoute
  '/analytics': typeof AnalyticsRoute
  '/expenses': typeof ExpensesRoute
  '/logs': typeof LogsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/trips': typeof TripsRoute
  '/vehicles': typeof VehiclesRoute
  '/logs/$id': typeof LogsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-fuel'
    | '/analytics'
    | '/expenses'
    | '/logs'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/trips'
    | '/vehicles'
    | '/logs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-fuel'
    | '/analytics'
    | '/expenses'
    | '/logs'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/trips'
    | '/vehicles'
    | '/logs/$id'
  id:
    | '__root__'
    | '/'
    | '/add-fuel'
    | '/analytics'
    | '/expenses'
    | '/logs'
    | '/notifications'
    | '/profile'
    | '/reports'
    | '/trips'
    | '/vehicles'
    | '/logs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddFuelRoute: typeof AddFuelRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ExpensesRoute: typeof ExpensesRoute
  LogsRoute: typeof LogsRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  TripsRoute: typeof TripsRoute
  VehiclesRoute: typeof VehiclesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-fuel': {
      id: '/add-fuel'
      path: '/add-fuel'
      fullPath: '/add-fuel'
      preLoaderRoute: typeof AddFuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/$id': {
      id: '/logs/$id'
      path: '/$id'
      fullPath: '/logs/$id'
      preLoaderRoute: typeof LogsIdRouteImport
      parentRoute: typeof LogsRoute
    }
  }
}

interface LogsRouteChildren {
  LogsIdRoute: typeof LogsIdRoute
}

const LogsRouteChildren: LogsRouteChildren = {
  LogsIdRoute: LogsIdRoute,
}

const LogsRouteWithChildren = LogsRoute._addFileChildren(LogsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddFuelRoute: AddFuelRoute,
  AnalyticsRoute: AnalyticsRoute,
  ExpensesRoute: ExpensesRoute,
  LogsRoute: LogsRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  TripsRoute: TripsRoute,
  VehiclesRoute: VehiclesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
