version: "3.8"

services:
  db:
    image: postgres:15
    container_name: fuel_db
    restart: always
    environment:
      POSTGRES_USER: fuel_user
      POSTGRES_PASSWORD: Fuel@2026Secure
      POSTGRES_DB: fuel_db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: fuel_backend
    restart: always
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://fuel_user:Fuel%402026Secure@db:5432/fuel_db
    depends_on:
      - db

volumes:
  postgres_data:
